packages:
  - packages/*
  - packages/*/test-app
  - tests/app

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - laragram-precognition@0.1.0

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild

overrides:
  cookie: '>=0.7.0'
